defaults:
  master_name: "Federated Model"
  projected_crs: "EPSG:7855"
  geodetic_crs: "EPSG:4326"
  base_point:
    easting: 332942.8369 # Survey Point Easting
    northing: 5801895.4324 # Survey Point Northing
    height: 0.0
    unit: m

masters:
  - id: "BUW"
    name: SRL-WPD-TVC-NAP-MOD-XDE-BUW-000000"
    projected_crs: "EPSG:7855"
    geodetic_crs: "EPSG:4326"
    base_point:
      easting: 333800.4900  # Burwood PBP Easting
      northing: 5809101.4680  # Burwood PBP Northing
      height: 0.0
      unit: m

  - id: "IVS"
    name: SRL-WPD-TVC-NAP-MOD-XDE-ESF-000000"
    projected_crs: "EPSG:7855"
    geodetic_crs: "EPSG:4326"
    base_point:
      easting: 335700.4900  # IVS PBP Easting
      northing: 5807351.4680  # IVS PBP Northing
      height: 0.0
      unit: m

  - id: "SGW"
    name: SRL-WPD-TVC-NAP-MOD-XDE-GWY-000000"
    projected_crs: "EPSG:7855"
    geodetic_crs: "EPSG:4326"
    base_point:
      easting: 335700.4900  # SGWP Easting
      northing: 5807351.4680  # SGWP PBP Northing
      height: 0.0
      unit: m

  - id: "PWD"
    name: SRL-WPD-TVC-UPKW-MOD-XDE-PWD-000000"
    projected_crs: "EPSG:7855"
    geodetic_crs: "EPSG:4326"
    base_point:
      easting: 335700.4900  # PWD PBP Easting
      northing: 5807351.4680  # PWD PBP Northing
      height: 0.0
      unit: m
      

files:
  - pattern: "*-BUW-*"
    master: "BUW"

  - pattern: "*-ESF-*"
    master: "IVS"

  - pattern: "*-SGW-*"
    master: "SGW"

